abbr_dict = {r"(\d+\.) gr\.(\W|$)": r"\g<1> grein\g<2>",
			 r"(\d+\.) mgr\.(\W|$)": r"\g<1> málsgrein\g<2>",
			 r"(\d+\.) nmgr\.(\W|$)": r"\g<1> neðanmálsgrein\g<2>",
			 r"(\W|^)[Ii]nnsk\. (blm\.|blaðamanns)": r"\g<1>innskot \g<2>",
			 r"(\W|^)([Ii]nnsk(\.|ot) )(blm\.)(\W|$)": r"\g<1>\g<2>blaðamanns \g<5>",
			 r" ([Ff]\.[Kk]r\.?)(\W|$)": r" fyrir Krist\g<2>",
			 r" ([Ee]\.[Kk]r\.?)(\W|$)": r" eftir Krist\g<2>",
			 r"(\W|^)([Cc]a|CA)\.?(\W|$)": r"\g<1>sirka\g<3>",
			 r"(\d+\.) [Ss]ek\.?(\W|$)": r"\g<1> sekúnda\g<2>",
			 r"(\d+\.) [Mm]ín\.?(\W|$)": r"\g<1> mínúta\g<2>",
			 r"(\W|^)(\d{1,2}\/\d{1,2} )frák\.?(\W|$)": r"\g<1>\g<2>fráköst\g<3>",
			 r"(\W|^)(\d{1,2} )stoðs\.?(\W|$)": r"\g<1>\g<2>stoðsendingar\g<3>",
			 r"(\W|^)([Nn]\.?k|N\.?K)\.?(\W|$)": r"\g<1>næstkomandi\g<3>",
			 r"(?i)(\W|^)(atr\.?)(\W|$)": r"\g<1>atriði\g<3>",
			 r"(?i)(\W|^)(ath\.?)(\W|$)": r"\g<1>athugið\g<3>",
			 r"(?i)(\W|^)(aths\.?)(\W|$)": r"\g<1>athugasemd\g<3>",
			 r"(\W|^)([Ff]\.?hl|F\.HL)\.?(\W|$)": r"\g<1>fyrri hluti\g<3>",
			 r"(\W|^)([Ss]\.?hl|S\.HL)\.?(\W|$)": r"\g<1>síðari hluti\g<3>",
			 r"(?i)(\W|^)(e\.?h\.?f\.?)(\W|$)": r"\g<1>E H F\g<3>",
			 r"(?i)(\W|^)(o\.?h\.?f\.?)(\W|$)": r"\g<1>O H F\g<3>",
			 r"(?i)(\W|^)(h\.?f\.?)(\W|$)": r"\g<1>H F\g<3>",
			 r"(?i)(\W|^)(s\.?f\.?)(\W|$)": r"\g<1>S F\g<3>",
			 r"(?i)(\W|^)(q\.?e\.?d\.?)(\W|$)": r"\g<1>Q E D\g<3>",
			 r"(\W|^)([Pp]\.?s\.?)(\W|$)": r"\g<1>P S\g<3>",
			 r"(\W|^)([Aa]\.?m\.?k|A\.?M\.?K)\.?(\W|$)": r"\g<1>að minnsta kosti\g<3>",
			 r"(\W|^)([Aa]\.m\.m\.?)(\W|$)": r"\g<1>að mínu mati\g<3>",
			 r"(\W|^)([Aa]\.n\.l\.?)(\W|$)": r"\g<1>að nokkru leyti\g<3>",
			 r"(\W|^)([Aa]lþm\.?)(\W|$)": r"\g<1>alþingismaður\g<3>",
			 r"(\W|^)([Aa]lm|ALM)\.?(\W|$)": r"\g<1>almennt\g<3>",
			 r"(\W|^)(bls\.?) (((\d{1,2}\.)?(\d{3}\.?)*\d+(,\d+)?|([Hh]undr[au]ð|HUNDR[AU]Ð|[Þþ]úsund|ÞÚSUND|[Mm]illjón(ir)?|MILLJÓN(IR)?))( )?)(\W|$)": r"\g<1>blaðsíða \g<3>\g<12>",
			 r"(?i)(\W|^)(B\.S[Cc]\.?)(\W|$)": r"\g<1>B S C\g<3>",
			 r"(?i)(\W|^)(M\.S[Cc]\.?)(\W|$)": r"\g<1>M S C\g<3>",
			 r"((\W|^)\() ?(e\.)(\W)": r"\g<1>enska\g<4>",
			 r"(\W|^)([Ee]\.k|E\.K)\.?(\W|$)": r"\g<1>einhvers konar\g<3>",
			 r"(\W|^)([Ee]\.?t\.?v\.?)(\W|$)": r"\g<1>ef til vill\g<3>",
			 r"(\W|^)([Ee]\-ð)(\W|$)": r"\g<1>eitthvað\g<3>",
			 r"(\W|^)([Ee]\-ju)(\W|$)": r"\g<1>einhverju\g<3>",
			 r"(\W|^)([Ee]\-s)(\W|$)": r"\g<1>einhvers\g<3>",
			 r"(\W|^)([Ee]\-r)(\W|$)": r"\g<1>einhver\g<3>",
			 r"(\W|^)([Ee]\-n)(\W|$)": r"\g<1>einhvern\g<3>",
			 r"(\W|^)([Ee]\-um)(\W|$)": r"\g<1>einhverjum\g<3>",
			 #r"(\W|^)(f\.) (^((([012]?[1-9]|3[01])\. ?)?(jan(úar)?|feb(rúar)?|mars?|apr(íl)?|maí|jú[nl]í?|ág(úst)?|sep(t(ember)?)?|okt(óber)?|nóv(ember)?|des(ember)?) )\d{2,4}$)(\W|$)": r"\g<1>fæddur \g<3>\g<4>",
			 # ABN: corrected pattern for 'fæddur', repeated with 'd.' for 'dáinn'. TODO: how to differentiate between genders? Spell checker?
			 # Note: the days pattern is somewhat flawed, 0. janúar would be a possible match ([0-9]), but we count on that pattern being sensible since the months are given as words
			 # correct if this causes problems. We keep the 0 to be able to match '10'.
			 r"(\W|^)(f\.) (([012]?[0-9]|3[01])\. ?)((jan(úar)?|feb(rúar)?|mars?|apr(íl)?|maí|jú[nl]í?|ág(úst)?|sep(t(ember)?)?|okt(óber)?|nóv(ember)?|des(ember)?) \d{2,4})(\W|$)": r"\g<1>fæddur \g<3>\g<5>\g<16>",
			 r"(\W|^)(d\.) (([012]?[0-9]|3[01])\. ?)((jan(úar)?|feb(rúar)?|mars?|apr(íl)?|maí|jú[nl]í?|ág(úst)?|sep(t(ember)?)?|okt(óber)?|nóv(ember)?|des(ember)?) \d{2,4})(\W|$)": r"\g<1>dáinn \g<3>\g<5>\g<16>",
			 r"(\W|^)([Ff]él\.)(\W|$)": r"\g<1>félag\g<3>",
			 r"(\W|^)([Ff]rh|FRH)\.?(\W|$)": r"\g<1>framhald\g<3>",
			 r"(\W|^)([Ff]rt|FRT)\.?(\W|$)": r"\g<1>framtíð\g<3>",
			 r"(\W|^)([Ff]\.o\.t\.)(\W|$)": r"\g<1>fyrir okkar tímatal\g<3>",
			 r"(\W|^)([Gg]\.?r\.?f|G\.?R\.?F)\.?(\W|$)": r"\g<1>gerum ráð fyrir\g<3>",
			 r"(\W|^)([Gg]\.?m\.?g|G\.?M\.?G)\.?(\W|$)": r"\g<1>guð minn góður\g<3>",
			 r"(\W|^)([Hh]dl\.?)(\W|$)": r"\g<1>héraðsdómslögmaður\g<3>",
			 r"(\W|^)([Hh]rl\.?)(\W|$)": r"\g<1>hæstaréttarlögmaður\g<3>",
			 r"(\W|^)([Hh]öf|HÖF)\.?(\W|$)": r"\g<1>höfundur\g<3>",
			 r"(\W|^)([Hh]v?k)(\W|$)": r"\g<1>hvorugkyn\g<3>",
			 r"(\W|^)([Hh]r\.?)(\W|$)": r"\g<1>herra\g<3>",
			 r"(\W|^)([Hh]v\.?)(\W|$)": r"\g<1>háttvirtur\g<3>",
			 r"(\W|^)([Hh]\.u\.b|H\.U\.B)\.?(\W|$)": r"\g<1>hér um bil\g<3>",
			 r"(\W|^)([Kk]k)(\W|$)": r"\g<1>karlkyn\g<3>",
			 r"(\W|^)([Kk]vk)(\W|$)": r"\g<1>kvenkyn\g<3>",
			 r"(\W|^)([Kk]t\.?)(:| \d{6}\-?\d{4})(\W|$)": r"\g<1>kennitala\g<3>\g<4>",
			 r"(\W|^)([Kk]l ?(\.|\:)?)(\s?\d{1,2}([:\.]\d{2})?)": r"\g<1>klukkan \g<4>",
			 r"(?i)(\W|^)kl ?(\.|\:)? ?((núll|eitt|tvö|þrjú|fjögur|fimm|sex|sjö|átta|níu|tíu|ellefu|tólf|((þret|fjór|fimm|sex)tán)|((sau|á|ní)tján)|tuttugu( og (eitt|tvö|þrjú|fjögur))?) )": r"klukkan \g<2>",
			 r"(\W|^)([Kk]höfn|[Kk]bh|KBH)(\W|$)": r"\g<1>Kaupmannahöfn\g<3>",
			 r"(\W|^)([Ll]h\.?nt\.?)(\W|$)": r"\g<1>lýsingarháttur nútíðar\g<3>",
			 r"(\W|^)([Ll]h\.?þt\.?)(\W|$)": r"\g<1>lýsingarháttur þátíðar\g<3>",
			 r"(\W|^)([Ll]td|LTD)\.?(\W|$)": r"\g<1>limited\g<3>",
			 r"(\W|^)([Mm]\.a\.)(\W|$)": r"\g<1>meðal annars\g<3>",
			 r"(\W|^)([Mm]\.a\.s|M\.A\.S)\.?(\W|$)": r"\g<1>meira að segja\g<3>",
			 r"(\W|^)([Mm]\.a\.o|M\.A\.O)\.?(\W|$)": r"\g<1>meðal annarra orða\g<3>",
			 r"((\d{1,2}\.)?(\d{3}\.?)*\d+(,\d+)?|([Hh]undr[au]ð|HUNDR[AU]Ð|[Þþ]úsund|ÞÚSUND|[Mm]illjón(ir)?|MILLJÓN(IR)?)) ?([Mm]\.y\.s\.?)(\W|$)": r"\g<1> metra yfir sjávarmáli\g<9>",
			 r"([02-9] )([Mm]illj\.?)(\W|$)": r"\g<1>milljónir\g<3>",
			 r"(1 )([Mm]illj\.?)(\W|$)": r"\g<1>milljónir\g<3>",
			 r"(\W|^)([Mm]\.?v\.?)(\W|$)": r"\g<1>miðað við\g<3>",
			 r"(\W|^)([Mm]\.?t\.?t|M\.?T\.?T)\.?(\W|$)": r"\g<1>með tilliti til\g<3>",
			 r"(\W|^)([Mm]\.?ö\.?o|M\.?Ö\.?O)\.?(\W|$)": r"\g<1>með öðrum orðum\g<3>",
			 r"(\W|^)([Mm]fl|MFL)\.?(\W|$)": r"\g<1>meistaraflokkur\g<3>",
			 r"((\d{1,2}\.)?(\d{3}\.?)*\d+(,\d+)?|([Hh]undr[au]ð|HUNDR[AU]Ð|[Þþ]úsund|ÞÚSUND|[Mm]illjón(ir)?|MILLJÓN(IR)?)) ?(m ?\^ ?2)(\W|$)": r"\g<1> fermetrar\g<9>",
			 r"((\d{1,2}\.)?(\d{3}\.?)*\d+(,\d+)?|([Hh]undr[au]ð|HUNDR[AU]Ð|[Þþ]úsund|ÞÚSUND|[Mm]illjón(ir)?|MILLJÓN(IR)?)) ?(m ?\^ ?3)(\W|$)": r"\g<1> rúmmetrar\g<9>",
			 r"(\W|^)([Nn]úv\.?)(\W|$)": r"\g<1>núverandi\g<3>",
			 r"(\W|^)([Nn]\.?t\.?t|N\.?T\.T)\.?(\W|$)": r"\g<1>nánar tiltekið\g<3>",
			 r"(\W|^)([Nn]kl|NKL)(\W|$)": r"\g<1>nákvæmlega\g<3>",
			 r"(\W|^)([Oo]\.?fl|O\.?FL)\.?(\W|$)": r"\g<1>og fleira\g<3>",
			 r"(\W|^)([Oo]\.?m\.?fl|O\.?M\.?FL)\.?(\W|$)": r"\g<1>og margt fleira\g<3>",
			 r"(\W|^)([Oo]\.?s\.?frv?|O\.?S\.?FRV?)\.?(\W|$)": r"\g<1>og svo framvegis\g<3>",
			 r"(\W|^)([Oo]\.?þ\.?h|O\.?Þ\.?H)\.?(\W|$)": r"\g<1>og þess háttar\g<3>",
			 r"(\W|^)([Oo]\.þ\.u\.l|O\.Þ\.U\.L)\.?(\W|$)": r"\g<1>og því um líkt\g<3>",
			 r"(\W|^)(([Ss]íma)?nr\.?) ": r"\g<1>\g<3>númer ",
			 r"(\W|^)([Pp]k\.?)(\W|$)": r"\g<1>pakki\g<3>",
			 r"(\W|^)([Rr]n\.?)(:| [\d\-]+)(\W|$)": r"\g<1>reikningsnúmer\g<3>\g<4>",
			 r"(\W|^)([Rr]itstj\.?)(\W|$)": r"\g<1>ritstjóri\g<3>",
			 r"(\W|^)([Rr]slm\.?)(\W|$)": r"\g<1>rannsóknarlögreglumaður\g<3>",
			 r"(\W|^)([Rr]ví?k|RVÍ?K)(\W|$)": r"\g<1>Reykjavík\g<3>",
			 r"(\W|^)([Ss]\.?)(:| \d{3}\-?\d{4}|\d{7})(\W|$)": r"\g<1>sími\g<3>\g<4>",
			 r"(\W|^)([Ss]br\.?)(\W)": r"\g<1>samanber\g<3>",
			 r"(\W|^)([Ss]\.?l\.?|SL\.)(\W|$)": r"\g<1>síðastliðinn\g<3>",
			 r"(\W|^)([Ss]\.?k\.?)(\W|$)": r"\g<1>svokallað\g<3>",
			 r"(\W|^)([Ss]kv|SKV)\.?(\W|$)": r"\g<1>samkvæmt\g<3>",
			 r"(\W|^)([Ss]\. ?s\.?)(\W|$)": r"\g<1>svo sem\g<3>",
			 r"(\W|^)([Ss]amþ|SAMÞ)\.?(\W|$)": r"\g<1>samþykki\g<3>",
			 r"(\W|^)([Ss]gt\.?)(\W|$)": r"\g<1>sergeant\g<3>",
			 r"(\W|^)([Ss]t\.?)(\W|$)": r"\g<1>saint\g<3>",
			 r"(\W|^)([Ss]ltjn|SLTJN)\.?(\W|$)": r"\g<1>Seltjarnarnes\g<3>",
			 r"(\W|^)([Ss]thlm|STHLM)(\W|$)": r"\g<1>Stokkhólmur\g<3>",
			 r"(\W|^)([Tt]bl|TBL)\.?(\W|$)": r"\g<1>tölublað\g<3>",
			 r"(\W|^)([Tt]l\.?)(\W|$)": r"\g<1>tengiliður\g<3>",
			 r"(\W|^)([Tt]\.h\.?)(\W|$)": r"\g<1>til hægri\g<3>",
			 r"(\W|^)([Tt]\.v\.?)(\W|$)": r"\g<1>til vinstri\g<3>",
			 r"(\W|^)([Tt]\.a\.m|T\.A\.M)\.?(\W|$)": r"\g<1>til að mynda\g<3>",
			 r"(\W|^)([Tt]\.?d|T\.?D)\.?(\W|$)": r"\g<1>til dæmis\g<3>",
			 r"(\W|^)([Uu]\.?þ\.?b|U\.?Þ\.?B)\.?(\W|$)": r"\g<1>um það bil\g<3>",
			 r"(\W|^)([Uu]ppl|UPPL)\.?(\W|$)": r"\g<1>upplýsingar\g<3>",
			 r"(\W|^)([Uu]td|UTD)\.?(\W|$)": r"\g<1>united\g<3>",
			 r"(\W|^)([Vv]s|VS)\.?(\W|$)": r"\g<1>versus\g<3>",
			 r"(\W|^)([Vv]sk\.?)(\W|$)": r"\g<1>virðisaukaskatt\g<3>",
			 r"(\W|^)([Ff]\.h\.?)(\W|$)": r"\g<1>fyrir hönd\g<3>",
			 r"(\W|^)([Dd]r\.?)(\W|$)": r"\g<1>doktor\g<3>",
			 r"([A-ZÁÐÉÍÓÚÝÞÆÖa-záðéíóúýþæö]+ )([Jj]r)\.?(\W|$)": r"\g<1>junior\g<3>",
			 r"(\W|^)([Þþ]f\.?)(\W|$)": r"\g<1>þolfall\g<3>",
			 r"(\W|^)([Þþ]gf\.?)(\W|$)": r"\g<1>þágufall\g<3>",
			 r"(\W|^)([Þþ]lt\.?)(\W|$)": r"\g<1>þáliðin tíð\g<3>",
			 r"(\W|^)([Þþ]\.á\.)(\W|$)": r"\g<1>þessa árs\g<3>",
			 r"(\W|^)([Þþ]\.h\.)(\W|$)": r"\g<1>þess háttar\g<3>",
			 r"(\W|^)([Þþ]\.m\.)(\W|$)": r"\g<1>þessa mánaðar\g<3>",
			 r"(\W|^)([Þþ]\.?e\.?a\.?s|Þ\.?E\.?A\.?S)\.?(\W|$)": r"\g<1>það er að segja\g<3>",
			 r"(\W|^)([Þþ]\.e\.)(\W|$)": r"\g<1>það er\g<3>",
			 r"(\W|^)([Þþ]\.?þ\.?a\.?a|Þ\.?Þ\.?A\.?A)\.?(\W|$)": r"\g<1>þá og því aðeins að\g<3>",
			 r"(\W|^)([Þþ]\.a\.l|Þ\.A\.L)\.?(\W|$)": r"\g<1>þar af leiðandi\g<3>",
			 r"(\W|^)([Þþ]\.a\.?)(\W|$)": r"\g<1>þannig að\g<3>",
			 r"(\W|^)([Þþ]\.u\.l|Þ\.U\.L)\.?(\W|$)": r"\g<1>því um líkt\g<3>",
			 r"(\W|^)([þÞ]\.á(\.| )m|Þ\.Á(\.| )M)\.?(\W|$)": r"\g<1>þar á meðal\g<3>",
			 r"(\W|^)([Þþ]\.m\.t|Þ\.M\.T)\.?(\W|$)": r"\g<1>þar með talið\g<3>",
			 r"(((((\d{1,2}\.)?(\d{3}\.)*\d{3}|\d+)(,\d+)?|([Hh]undr[au]ð|HUNDR[AU]Ð|[Þþ]úsund|ÞÚSUND|[Mm]illjón(ir)?|MILLJÓN(IR)?))( )?)\s)(þús\.?)( [A-ZÁÐÉÍÓÚÝÞÆÖa-záðéíóúýþæö]*)?": r" \g<1>þúsund\g<13>",
			 r"([Mm]örg )þús\.?( [A-ZÁÐÉÍÓÚÝÞÆÖa-záðéíóúýþæö]*)?": r" \g<1>þúsund\g<2>",
			 r"(\d+\.) [Áá]rg\.(\W|$)": r"\g<1> árgangur\g<2>",
			 r"(\W|^)([Óó]ákv\.gr\.)(\W|$)": r"\g<1>óákveðinn greinir\g<3>",
			 r"(\d+\.) útg\.(\W|$)": r"\g<1> útgáfa\g<2>",
			 r"(\W|^)([Íí]sl|ÍSL)\.?(\W|$)": r"\g<1>íslenska\g<3>",
			 r"([02-9])( )?°C(\W|$)": r"\g<1> gráður á selsíus\g<3>",
			 r"(1)( )?°C(\W|$)": r"\g<1> gráða á selsíus\g<3>",
			 r"([02-9])( )?°F(\W|$)": r"\g<1> gráður á fahrenheit\g<3>",
			 r"(1)( )?°F(\W|$)": r"\g<1> gráða á fahrenheit\g<3>",
			 r"([02-9])( )?°W(\W|$)": r"\g<1> gráður vestur\g<3>",
			 r"(1)( )?°W(\W|$)": r"\g<1> gráða vestur\g<3>",
			 r"([02-9])( )?°N(\W|$)": r"\g<1> gráður norður\g<3>",
			 r"(1)( )?°(\W|$)": r"\g<1> gráða norður\g<3>",
			 r"([02-9])( )?°E(\W|$)": r"\g<1> gráður austur\g<3>",
			 r"(1)( )?°E(\W|$)": r"\g<1> gráða austur\g<3>",
			 r"([02-9])( )?°S(\W|$)": r"\g<1> gráður suður\g<3>",
			 r"(1)( )?°S(\W|$)": r"\g<1> gráða suður\g<3>"}