symb_dict = {
    r"&": "og",
    r" / ": " skástrik ",
    r"\+": " plús ",
    r"=": " jafnt og ",
    r"≠": " ekki jafnt og ",
    r"ε": " epsilon ",
    r"^\±|\∓$": " plús mínus ",
    r"^\~|\≈$": " um það bil ",
    r"→": " þar af leiðandi ",
    r"≡": " skilgreint sem",
    r" < ": " minna en ",
    r" > ": " stærra en ",
    r"≤": " minna en eða jafnt og ",
    r"≥": " stærra en eða jafnt og ",
    r"∞": " óendanlegt ",
    r"°": " gráður ",
    r"^(Α|α)$": " alfa",
    r"^(Β|β)$": " beta",
    r"^(Γ|γ)$": " gamma",
    r"^(Δ|δ)$": " delta",
    r"^(Ε|ε)$": " epsilon",
    r"^(Ζ|ζ)$": " zeta",
    r"^(Η|η)$": " eta",
    r"^(Θ|θ)$": " þeta",
    r"^(Ι|ι)$": " jóta",
    r"^(Κ|κ)$": " kappa",
    r"^(Λ|λ)$": " lambda",
    r"^(Μ|μ)$": " mý",
    r"^(Ν|ν)$": " ný",
    r"^(Ξ|ξ)$": " xí",
    r"^(Ο|ο)$": " ómíkrón",
    r"^(Π π)$": " pí",
    r"^(Ρ|ρ)$": " hró",
    r"^(Σ|σ)$": " sigma",
    r"^(Τ|τ)$": " tá",
    r"^(Υ|υ)$": " upsílon",
    r"^(Φ|φ)$": " fí",
    r"^(Χ|χ)$": " kí",
    r"^(Ψ|ψ)$": " psí",
    r"^(Ω|ω)$": " ómega",
}
